#Opensearch 
opensearch:
  One:
    host: ["https://10.11.233.102:9200"]
    username: "admin"
    password: "systex123!GG"

#RabbitMQ

#Const

const:
  httpRetrySecond: 5
  index: "blackbox_snmp" #opensearch index

